// Centralized examination fields to avoid require cycle
export const EXAMINATION_FIELDS = [
  { key: "pallor", label: "Pallor" },
  { key: "koilonychia", label: "Koilonychia" },
  { key: "leukonychia", label: "Leukonychia" },
  { key: "clubbing", label: "Clubbing" },
  { key: "bilateralPedalEdema", label: "Bilateral Pedal Edema" },
  { key: "spine", label: "Spine" },
  { key: "abnormalSpine", label: "Abnormal Spine Reason" },
  { key: "lymphNodes", label: "Lymph Nodes" },
  { key: "sizeComparison", label: "Breast Size Comparison" },
  { key: "nippleDischarge", label: "Nipple Discharge" },
  { key: "swelling", label: "Swelling" },
  { key: "nippleDeformity", label: "Nipple Deformity" },
  { key: "shapeOfAbdomen", label: "Shape of Abdomen" },
  { key: "umbilicus", label: "Umbilicus" },
  { key: "striae", label: "Striae" },
  { key: "prominentVeins", label: "Prominent Veins" },
  { key: "pulsations", label: "Pulsations" },
  { key: "abdominalWallEdema", label: "Abdominal Wall Edema" },
  { key: "hernialOrfices", label: "Hernial Orifices" },
  { key: "fundalHeight", label: "Fundal Height" },
  { key: "lie", label: "Lie" },
  { key: "presentation", label: "Presentation" },
  { key: "estimatedFetalWeight", label: "Estimated Fetal Weight" },
  { key: "liquor", label: "Liquor" },
  { key: "scarTenderness", label: "Scar Tenderness" },
  { key: "fetalHeartRate", label: "Fetal Heart Rate" },
  { key: "perSpeculumFindings", label: "Per Speculum" },
  { key: "perVaginalFindings", label: "Per Vaginal" },
];
